reporter: "xcode"

excluded:
  - DerivedData
  - Pods
  - "EurofurenceModel/Public/Default Dependency Implementations/Core Data Store/Model Adaptation/*.swift"

disabled_rules:
  - identifier_name
  - type_name
  - weak_delegate
  - trailing_whitespace
  - class_delegate_protocol
  - todo

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - last_where
  - legacy_multiple
  - mark
  - modifier_order

force_try:
  severity: error

force_unwrapping:
  severity: error

line_length:
  warning: 180
  ignores_comments: true

type_body_length:
  warning: 400

