excluded:
  - DerivedData
  - Pods
  - "EurofurenceModel/Public/Default Dependency Implementations/Core Data Store/Model Adaptation/*.swift"

disabled_rules:
  - identifier_name
  - type_name
  - weak_delegate
  - trailing_whitespace
  - class_delegate_protocol
  - todo

opt_in_rules:
  - force_unwrapping

line_length:
  warning: 180
  ignores_comments: true

type_body_length:
  warning: 400

